config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  resources :activities
  get '/analytics' => 'analytics#index'
  get '/charts/data' => 'analytics#get_case'

  authenticated :user do
    mount Resque::Server.new, at: '/resque'
  end

  get 'reports' => 'reports#index', as: :reports
  get 'reports/show' => 'reports#show', as: :report_show
  get 'reports/all_leads_by_channel' => 'reports#leads_by_channel_report', as: :reports_leads_by_channel
  get 'reports/all_leads_detail/(:marketing_channel_arg)(.:format)' => 'reports#leads_detail_report', as: :reports_leads_detail
  get 'reports/cases_statute_of_limitations' => 'reports#case_sol_report', as: :reports_case_sol
  get 'reports/open_close' => 'reports#open_close_report', as: :reports_open_close
  get 'reports/medical_bills_totals' => 'reports#medical_bills_report', as: :reports_medical_bills
  get 'reports/cases_by_user' => 'reports#cases_by_user_report', as: :reports_cases_by_user
  get 'reports/cases_by_statuses' => 'reports#cases_by_status_report', as: :reports_cases_by_status
  get 'reports/count_of_cases_by_statuses' => 'reports#count_of_cases_by_status_report', as: :reports_count_of_cases_by_status
  get 'reports/open_close_detail_report' => 'reports#open_close_detail_report', as: :reports_open_close_detail

  resources :company_olds
  resources :templates
  patch 'templates/update_html/:id' => 'templates#update_html'
  get 'templates/generate_document/:id' => 'templates#generate_document', as: :generate_document
  post 'templates_get_case' => 'templates#get_case', as: :get_case
  post 'templates_get_addressee' => 'templates#get_addressee', as: :get_addressee_attrs
  post 'templates_generate_docx' => 'templates#generate_docx', as: :generate_docx
  post 'settlement_generate_docx' => 'settlements#generate_docx', as: :settlement_generate_docx
  get 'settlement_download_docx/:id' => 'settlements#download_docx', as: :settlement_download_docx
  get 'download_docx/:id' => 'templates#download_docx', as: :download_docx
  post 'upload_docx' => 'templates#upload_docx', as: :upload_docx

  resources :time_entries, :except => [:new]
  put 'set_timer' => 'time_entries#set_timer', as: :set_timer
  put 'get_timer' => 'time_entries#get_timer', as: :get_timer
  put 'reset_timer' => 'time_entries#reset_timer', as: :reset_timer

  resources :task_lists
  post 'task_lists/import_to_case' => 'task_lists#import_to_case', as: :task_lists_import_to_case
  resources :firms
  resources :notes

  get '/documents/preview/:id' => 'documents#preview'
  resources :documents
  resources :plans
  get 'subscriptions/:id/change_plan/:plan_id' => 'subscriptions#change_plan', as: :change_plan
  get 'subscriptions/:id/edit_card/' => 'subscriptions#edit_card', as: :edit_card
  resources :subscriptions
  mount StripeEvent::Engine => '/payment-webhook'
  get '/events/email' => 'events#emails_autocomplete'
  resources :events

  resources :client_intakes, as: 'leads'
  get '/client_intakes_contacts/:id' => 'client_intakes#show_lead_contact', as: :lead_contact
  get '/client_intakes_contacts/:id/edit' => 'client_intakes#edit_lead_contact', as: :edit_lead_contact
  get '/client_intakes_documents/:id' => 'client_intakes#lead_documents', as: :lead_documents
  get '/client_intakes/:id/acceptance_letter' => 'client_intakes#acceptance_letter', as: :acceptance_letter

  resources :tasks
  post 'tasks/complete_task' => 'tasks#complete_task'
  get 'get_tasks' => 'tasks#get_tasks', as: :get_tasks
  match "/notifications/remove_all", to: "notifications#remove_all", via: [:delete], as: :remove_all_notifications
  resources :notifications


  resources :contacts
  post '/contacts/fly_create_contact' => 'contacts#fly_create_contact' ,as: :fly_contact, :defaults => { :format => :json }
  get '/companies' => 'contacts#companies', as: :companies
  get '/companies/:id' => 'contacts#show_company', as: :company
  get '/companies/:id/edit' => 'contacts#edit_company', as: :edit_company

  resources :insights do
    collection do
      get :filter_cases
    end
  end
  
  authenticated :user do
    root :to => "dashboards#new", as: :user_root
    #root :to => 'business_account#dashboard', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Business' }, :as => "business_root"
  end

  root :to => "visitors#index"
  get '/onboarding' => 'dashboards#new'
  post '/save_confirm_step' => 'dashboards#save_step'
  get '/finish_registration' => 'dashboards#finish_registration'
  get '/dashboard/:id' => 'dashboards#show'
  get '/get_counties_by_state' => 'insights#get_counties_by_state'
  #post '/dashboard/:name' => 'dashboard#create_firm_contact', as: 'dashboard_create_firm_contact'
  #get '/dashboard/:id' => 'users#show', as: :user_root
  get '/auth/google_oauth2/callback' => 'users#save_google_oauth'
  get '/auth/failure' => 'users#fail_google_oauth'
  get 'refresh_events' => 'events#refresh_events'
  # get '/dashboards/select_calendar'
  post '/dashboards/select_calendar'
  get  "dropbox/main"
  post "dropbox/upload"
  get  "dropbox/auth_start"
  get  "dropbox/auth_finish"
  get 'login_callback' => 'nylas#login_callback'
  get 'login_callback_close' => 'nylas#login_callback_close'
  get 'login' => 'nylas#login'
  resources :namespaces
  post 'get_events' => 'namespaces#get_events', as: :get_events
  post 'get_calendars' => 'namespaces#get_calendars', as: :get_calendars
  post 'get_mass_calendar_events' => 'namespaces#get_mass_calendar_events', as: :get_mass_calendar_events
  delete 'namespaces/:id/:calendar_id' => 'namespaces#destroy_calendar', as: :calendar

  # Visitor routes
  get "/about" => 'visitors#about', as: :about
  get "/terms" => 'visitors#terms', as: :terms
  get "index" => 'visitors', as: :index
  get "/contact" => 'visitors#contactlitigo', as: :contactlitigo
  get "/privacy" => 'visitors#privacy', as: :privacy
  get "/pricing" => 'visitors#pricing', as: :pricing
  get "/partners" => 'visitors#partners', as: :partners
  get "/confirm" => 'visitors#confirm_signin_email', as: :confirm_signin_email

  resources :dashboards, path: "dashboard"

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions" , :invitations => 'invitations'}
  devise_scope :user do
    get 'users/profile' => 'registrations#profile'
    get 'users/settings' => 'registrations#settings'
    get 'users/admin' => 'registrations#admin'
    get '/confirm/:id' => 'registrations#confirm_signup_email', as: :confirm_signup_email
    patch '/users/update_profile' => 'registrations#update_profile'
    get "/users/invitation/existing_user_invited/:id" => 'invitations#existing_user_invited', as: :existing_user_invited
    post "edit_events_permit" => 'invitations#edit_events_permit', as: :edit_events_permit

  end

  resources :expenses
  resources :invoices do
    resources :payments, :only => [:index, :create], :shallow => true

    get 'download' => 'invoices#download'
    get 'invoice_payments' => 'payments#invoice_payments', :defaults => { :format => :json }
  end
  resources :users
  resources :cases do
    resources :contacts, :shallow => true
    resources :notes, :shallow => true
    resources :documents#, :shallow => true
    resources :tasks, :shallow => true
    resources :incidents
    resources :resolutions
    resources :medicals
    resources :insurances
    resources :expenses
    resources :interrogatories
    resources :settlements
  end

  get 'cases/:id/edit_case_insurances' => 'insurances#edit_case_insurances', as: :edit_case_insurances
  get 'cases/:id/edit_case_interrogatories' => 'interrogatories#edit_case_interrogatories', as: :edit_case_interrogatories
  get "cases/:id/summary" => 'cases#summary', as: :case_summary
  get "cases/:id/dates" => 'cases#case_dates', as: :case_dates
  get "user_cases" => "cases#user_cases", :defaults => { :format => :json }
  get "user_leads" => "client_intakes#user_leads", :defaults => { :format => :json }
  get "user_notes" => "notes#user_notes", :defaults => { :format => :json }
  get "user_contacts" => "contacts#user_contacts", :defaults => { :format => :json }  
  get "case_user_notes/:case_id/notes" => "notes#case_user_notes", :defaults => { :format => :json }, as: :case_user_notes
  get "case_notes_case/:case_id/notes" => "notes#case_notes_case", :defaults => { :format => :json }, as: :case_notes_case
  get 'firm_invoices' => 'invoices#firm_invoices', :defaults => { :format => :json }
  get "accept_case/:id" => 'client_intakes#accept_case', as: :accept_case
  get 'cases/:id/doc' => 'cases#doc', as: :doc
  get "contacts/:id/contact information" => 'contacts#info', as: :contact_info
  get "contacts/:id/personal information" => 'contacts#personal', as: :contact_personal
  get "contacts/:id/company information" => 'contacts#coinfo', as: :contact_coinfo
  get "contacts/:id/cases" => 'contacts#contact_cases', as: :contact_linked_cases

  get 'cases/:case_id/assign_contacts' => 'contacts#assign_contacts', as: :assign_contacts
  post 'cases/:case_id/update_case_contacts' => 'contacts#update_case_contacts', as: :update_case_contacts
  post 'cases/:id/copy' => 'cases#create', as: :copy_case_create
  get 'cases/:id/case_contacts' => 'cases#show_case_contacts', as: :show_case_contacts
  get 'cases/:id/edit_case_contacts' => 'cases#edit_case_contacts', as: :edit_case_contacts
  post 'cases/:id/update_case_contacts' => 'cases#update_case_contacts', as: :update_contacts_on_case

  get 'cases/:id/case_services' => 'cases#case_services', as: :get_case_services
  get 'cases/:id/case_expenses' => 'cases#case_expenses', as: :get_case_expenses

  get 'invoice_expenses' => 'invoices#expenses', as: :show_invoice_expenses
  get 'invoice_services' => 'invoices#services', as: :show_invoice_services
  get 'invoice_sum' => 'invoices#invoice_sum', as: :show_invoice_sum

  resources :medicals do
    resources :injuries
  end
  get "emails_autocomplete" => "events#emails_autocomplete"
  get "sync_calendar" => "events#sync_calendar"

app/controllers/settlements_controller.rb
class SettlementsController < ApplicationController
  before_action :set_settlement, only: [:show, :edit, :update, :destroy, :generate_docx]
  before_action :set_user, :set_firm

  # GET /settlements
  # GET /settlements.json
  def index
    @settlements = Settlement.all
  end

  # GET /settlements/1
  # GET /settlements/1.json
  def show
  end

  # GET /settlements/new
  def new
    unless get_case
      redirect_to documents_path
      return
    end

    @settlement = Settlement.find_or_initialize_by case_id: params[:case_id]

    @settlement.user = @user
    @settlement.firm = @firm
    @settlement.case = @case
    @settlement.save

    @html = @settlement.fill_generated_html
  end

  # GET /settlements/1/edit
  def edit
    @settlement = Settlement.find_by case_id: params[:case_id]
    @settlement ||= Settlement.new(case_id: case_id)

    @settlement.user = @user
    @settlement.firm = @firm

    @html = Nokogiri::HTML(@settlement.html_content.html_safe)
  end

  # POST /settlements
  # POST /settlements.json
  def create
    @settlement = Settlement.new(settlement_params)

    respond_to do |format|
      if @settlement.save
        format.html { redirect_to @settlement, notice: 'Settlement was successfully created.' }
        format.json { render :show, status: :created, location: @settlement }
      else
        format.html { render :new }
        format.json { render json: @settlement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /settlements/1
  # PATCH/PUT /settlements/1.json
  def update
    respond_to do |format|
      if @settlement.update(settlement_params)
        format.html { redirect_to @settlement, notice: 'Settlement was successfully updated.' }
        format.json { render :show, status: :ok, location: @settlement }
      else
        format.html { render :edit }
        format.json { render json: @settlement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /settlements/1
  # DELETE /settlements/1.json
  def destroy
    @settlement.destroy
    respond_to do |format|
      format.html { redirect_to settlements_url, notice: 'Settlement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def generate_docx
    template_document = TemplateDocument.create({
                                                    html_content: params[:html],
                                                    name: 'Settlement_Statement',
                                                    template_id: @settlement.template_id,
                                                    firm_id: @firm.id,
                                                    user_id: @user.id
                                                })
    render :json => { success: true, id: template_document.id }
  end

  def download_docx
    template_document = TemplateDocument.find(params[:id])
    new_tmp_file_name = template_document.generate_docx
    respond_to do |format|
      format.docx do
        send_file new_tmp_file_name, :filename => "#{template_document.name}.docx"
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_settlement
      @settlement = Settlement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def settlement_params
      params[:settlement]
    end
end

app/helpers/settlements_helper.rb
module SettlementsHelper
end

app/views/settlements/_form.html.erb
<div id="show-buttons">
  <ul>
    <div id="temp-custom">
      <ul>
        <li>
          <%= link_to case_documents_path(case_id: @case.id), :class => 'dark' do %>
            <span id="temp" class="glyphicon glyphicon-arrow-left pull-right" title="Back to Documents"></span>
          <% end %>
        </li>
        <li><% link_to 'Edit', '#', id: 'preview_docx', class: 'dark' %></li>
        <li class="dropdown">
          <%= link_to "", class: 'dropdown-toggle action-button', id: 'generate_doc', data: {toggle: "dropdown"} do %>
            GENERATE DOCUMENT
            <span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1" style="margin-top: 10px;">
            <li><%= link_to "Download to local", '#', id: 'create_docx' %></li>
            <li><%= link_to 'Save directly to Litigo', '', id: 'save_to_app' %></li>
          </ul>
        </li>
      </ul>
    </div>
  </ul>
</div>
<div class="template_block" style="padding-top: 50px;">
  <div class="row">
    <div class="col-md-1 col-lg-2"></div>
    <div class="col-md-10 col-lg-8">
      <div class="template_html_show"><%= raw @html %></div>
    </div>
    <div class="col-md-1 col-lg-2"></div>
  </div>
  <!-- row end -->
</div>
<%= render :partial => "settlements_form_javascript" %>

app/views/settlements/_settlements_form_javascript.html.erb
<% content_for :javascript do %>
<script>
    $(document).ready(function () {
        $('#create_docx').click(function (e) {
            e.preventDefault();
            var html = $('.template_html_show').clone();
            html.find("select").remove();
            html.find(".custom_input").remove();
            html.find('.insertion').removeClass();
            $.ajax({
                url: "/settlement_generate_docx",
                type: 'POST',
                dataType: "json",
                data: {id: <%= @settlement.id %>, html: html[0].innerHTML},
                success: function(data){
                    var id = data.id;
                    window.location.href = '/settlement_download_docx/'+id+'.docx';
                }
            });
        });

        $('#save_to_app').click(function (e) {
            e.preventDefault();
            var html = $('.template_html_show').clone();
            var case_id = $('#case').val();
            html.find("select").remove();
            html.find(".custom_input").remove();
            html.find('.insertion').removeClass();
            $.ajax({
                url: "/upload_docx",
                type: 'POST',
                dataType: "json",
                data: {id: <%= @settlement.template_id %>, html: html[0].innerHTML, name: $('#template_name').val(), case_id: case_id },
                success: function (data) {
                    window.location.href = data.href;
                }
            });
        });

        var preview = true;
        $('#preview_docx').click(function (e) {
            e.preventDefault();
            preview = !preview;
            if (preview) {
                $('.template_html_show .custom_input').hide();
                $(this).text('Edit');
            } else {
                $('.template_html_show .custom_input').show();
                $(this).text('Preview');
            }
            $('.template-model').toggle();
            $('.template_html_show .insertion').toggleClass('white');
        })
    });
</script>
<script type='text/javascript'>
    $(function() {
        $('#name').tipsy({gravity: 's', fade: true});
        $('#cs-sel').tipsy({gravity: 's', fade: true});
        $('#addy').tipsy({gravity: 's', fade: true});
        $('#temp').tipsy({gravity: 'n', fade: true});
    });
</script>
<% end %>

app/views/settlements/edit.html.erb
<h1>Editing Settlement</h1>

<%= render 'form' %>

<%= link_to 'Show', @settlement %> |
<%= link_to 'Back', settlements_path %>

app/views/settlements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Settlements</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @settlements.each do |settlement| %>
      <tr>
        <td><%= link_to 'Show', settlement %></td>
        <td><%= link_to 'Edit', edit_settlement_path(settlement) %></td>
        <td><%= link_to 'Destroy', settlement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Settlement', new_settlement_path %>

app/views/settlements/new.html.erb
<%= render 'form' %>

app/views/settlements/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_settlement_path(@settlement) %> |
<%= link_to 'Back', settlements_path %>