config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  resources :activities
  get '/analytics' => 'analytics#index'
  get '/charts/data' => 'analytics#get_case'

  authenticated :user do
    mount Resque::Server.new, at: '/resque'
  end

  get 'reports' => 'reports#index', as: :reports
  get 'reports/show' => 'reports#show', as: :report_show
  get 'reports/all_leads_by_channel' => 'reports#leads_by_channel_report', as: :reports_leads_by_channel
  get 'reports/all_leads_detail/(:marketing_channel_arg)(.:format)' => 'reports#leads_detail_report', as: :reports_leads_detail
  get 'reports/cases_statute_of_limitations' => 'reports#case_sol_report', as: :reports_case_sol
  get 'reports/open_close' => 'reports#open_close_report', as: :reports_open_close
  get 'reports/medical_bills_totals' => 'reports#medical_bills_report', as: :reports_medical_bills
  get 'reports/cases_by_user' => 'reports#cases_by_user_report', as: :reports_cases_by_user
  get 'reports/cases_by_statuses' => 'reports#cases_by_status_report', as: :reports_cases_by_status
  get 'reports/count_of_cases_by_statuses' => 'reports#count_of_cases_by_status_report', as: :reports_count_of_cases_by_status
  get 'reports/open_close_detail_report' => 'reports#open_close_detail_report', as: :reports_open_close_detail

  resources :company_olds
  resources :templates
  patch 'templates/update_html/:id' => 'templates#update_html'
  get 'templates/generate_document/:id' => 'templates#generate_document', as: :generate_document
  post 'templates_get_case' => 'templates#get_case', as: :get_case
  post 'templates_get_addressee' => 'templates#get_addressee', as: :get_addressee_attrs
  post 'templates_generate_docx' => 'templates#generate_docx', as: :generate_docx
  post 'settlement_generate_docx' => 'settlements#generate_docx', as: :settlement_generate_docx
  get 'settlement_download_docx/:id' => 'settlements#download_docx', as: :settlement_download_docx
  get 'download_docx/:id' => 'templates#download_docx', as: :download_docx
  post 'upload_docx' => 'templates#upload_docx', as: :upload_docx

  resources :time_entries, :except => [:new]
  put 'set_timer' => 'time_entries#set_timer', as: :set_timer
  put 'get_timer' => 'time_entries#get_timer', as: :get_timer
  put 'reset_timer' => 'time_entries#reset_timer', as: :reset_timer

  resources :task_lists
  post 'task_lists/import_to_case' => 'task_lists#import_to_case', as: :task_lists_import_to_case
  resources :firms
  resources :notes

  get '/documents/preview/:id' => 'documents#preview'
  resources :documents
  resources :plans
  get 'subscriptions/:id/change_plan/:plan_id' => 'subscriptions#change_plan', as: :change_plan
  get 'subscriptions/:id/edit_card/' => 'subscriptions#edit_card', as: :edit_card
  resources :subscriptions
  mount StripeEvent::Engine => '/payment-webhook'
  get '/events/email' => 'events#emails_autocomplete'
  resources :events

  resources :client_intakes, as: 'leads'
  get '/client_intakes_contacts/:id' => 'client_intakes#show_lead_contact', as: :lead_contact
  get '/client_intakes_contacts/:id/edit' => 'client_intakes#edit_lead_contact', as: :edit_lead_contact
  get '/client_intakes_documents/:id' => 'client_intakes#lead_documents', as: :lead_documents
  get '/client_intakes/:id/acceptance_letter' => 'client_intakes#acceptance_letter', as: :acceptance_letter

  resources :tasks
  post 'tasks/complete_task' => 'tasks#complete_task'
  get 'get_tasks' => 'tasks#get_tasks', as: :get_tasks
  match "/notifications/remove_all", to: "notifications#remove_all", via: [:delete], as: :remove_all_notifications
  resources :notifications


  resources :contacts
  post '/contacts/fly_create_contact' => 'contacts#fly_create_contact' ,as: :fly_contact, :defaults => { :format => :json }
  get '/companies' => 'contacts#companies', as: :companies
  get '/companies/:id' => 'contacts#show_company', as: :company
  get '/companies/:id/edit' => 'contacts#edit_company', as: :edit_company

  resources :insights do
    collection do
      get :filter_cases
    end
  end
  
  authenticated :user do
    root :to => "dashboards#new", as: :user_root
    #root :to => 'business_account#dashboard', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Business' }, :as => "business_root"
  end

  root :to => "visitors#index"
  get '/onboarding' => 'dashboards#new'
  post '/save_confirm_step' => 'dashboards#save_step'
  get '/finish_registration' => 'dashboards#finish_registration'
  get '/dashboard/:id' => 'dashboards#show'
  get '/get_counties_by_state' => 'insights#get_counties_by_state'
  #post '/dashboard/:name' => 'dashboard#create_firm_contact', as: 'dashboard_create_firm_contact'
  #get '/dashboard/:id' => 'users#show', as: :user_root
  get '/auth/google_oauth2/callback' => 'users#save_google_oauth'
  get '/auth/failure' => 'users#fail_google_oauth'
  get 'refresh_events' => 'events#refresh_events'
  # get '/dashboards/select_calendar'
  post '/dashboards/select_calendar'
  get  "dropbox/main"
  post "dropbox/upload"
  get  "dropbox/auth_start"
  get  "dropbox/auth_finish"
  get 'login_callback' => 'nylas#login_callback'
  get 'login_callback_close' => 'nylas#login_callback_close'
  get 'login' => 'nylas#login'
  resources :namespaces
  post 'get_events' => 'namespaces#get_events', as: :get_events
  post 'get_calendars' => 'namespaces#get_calendars', as: :get_calendars
  post 'get_mass_calendar_events' => 'namespaces#get_mass_calendar_events', as: :get_mass_calendar_events
  delete 'namespaces/:id/:calendar_id' => 'namespaces#destroy_calendar', as: :calendar

  # Visitor routes
  get "/about" => 'visitors#about', as: :about
  get "/terms" => 'visitors#terms', as: :terms
  get "index" => 'visitors', as: :index
  get "/contact" => 'visitors#contactlitigo', as: :contactlitigo
  get "/privacy" => 'visitors#privacy', as: :privacy
  get "/pricing" => 'visitors#pricing', as: :pricing
  get "/partners" => 'visitors#partners', as: :partners
  get "/confirm" => 'visitors#confirm_signin_email', as: :confirm_signin_email

  resources :dashboards, path: "dashboard"

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions" , :invitations => 'invitations'}
  devise_scope :user do
    get 'users/profile' => 'registrations#profile'
    get 'users/settings' => 'registrations#settings'
    get 'users/admin' => 'registrations#admin'
    get '/confirm/:id' => 'registrations#confirm_signup_email', as: :confirm_signup_email
    patch '/users/update_profile' => 'registrations#update_profile'
    get "/users/invitation/existing_user_invited/:id" => 'invitations#existing_user_invited', as: :existing_user_invited
    post "edit_events_permit" => 'invitations#edit_events_permit', as: :edit_events_permit

  end

  resources :expenses
  resources :invoices do
    resources :payments, :only => [:index, :create], :shallow => true

    get 'download' => 'invoices#download'
    get 'invoice_payments' => 'payments#invoice_payments', :defaults => { :format => :json }
  end
  resources :users
  resources :cases do
    resources :contacts, :shallow => true
    resources :notes, :shallow => true
    resources :documents#, :shallow => true
    resources :tasks, :shallow => true
    resources :incidents
    resources :resolutions
    resources :medicals
    resources :insurances
    resources :expenses
    resources :interrogatories
    resources :settlements
  end

  get 'cases/:id/edit_case_insurances' => 'insurances#edit_case_insurances', as: :edit_case_insurances
  get 'cases/:id/edit_case_interrogatories' => 'interrogatories#edit_case_interrogatories', as: :edit_case_interrogatories
  get "cases/:id/summary" => 'cases#summary', as: :case_summary
  get "cases/:id/dates" => 'cases#case_dates', as: :case_dates
  get "user_cases" => "cases#user_cases", :defaults => { :format => :json }
  get "user_leads" => "client_intakes#user_leads", :defaults => { :format => :json }
  get "user_notes" => "notes#user_notes", :defaults => { :format => :json }
  get "user_contacts" => "contacts#user_contacts", :defaults => { :format => :json }  
  get "case_user_notes/:case_id/notes" => "notes#case_user_notes", :defaults => { :format => :json }, as: :case_user_notes
  get "case_notes_case/:case_id/notes" => "notes#case_notes_case", :defaults => { :format => :json }, as: :case_notes_case
  get 'firm_invoices' => 'invoices#firm_invoices', :defaults => { :format => :json }
  get "accept_case/:id" => 'client_intakes#accept_case', as: :accept_case
  get 'cases/:id/doc' => 'cases#doc', as: :doc
  get "contacts/:id/contact information" => 'contacts#info', as: :contact_info
  get "contacts/:id/personal information" => 'contacts#personal', as: :contact_personal
  get "contacts/:id/company information" => 'contacts#coinfo', as: :contact_coinfo
  get "contacts/:id/cases" => 'contacts#contact_cases', as: :contact_linked_cases

  get 'cases/:case_id/assign_contacts' => 'contacts#assign_contacts', as: :assign_contacts
  post 'cases/:case_id/update_case_contacts' => 'contacts#update_case_contacts', as: :update_case_contacts
  post 'cases/:id/copy' => 'cases#create', as: :copy_case_create
  get 'cases/:id/case_contacts' => 'cases#show_case_contacts', as: :show_case_contacts
  get 'cases/:id/edit_case_contacts' => 'cases#edit_case_contacts', as: :edit_case_contacts
  post 'cases/:id/update_case_contacts' => 'cases#update_case_contacts', as: :update_contacts_on_case

  get 'cases/:id/case_services' => 'cases#case_services', as: :get_case_services
  get 'cases/:id/case_expenses' => 'cases#case_expenses', as: :get_case_expenses

  get 'invoice_expenses' => 'invoices#expenses', as: :show_invoice_expenses
  get 'invoice_services' => 'invoices#services', as: :show_invoice_services
  get 'invoice_sum' => 'invoices#invoice_sum', as: :show_invoice_sum

  resources :medicals do
    resources :injuries
  end
  get "emails_autocomplete" => "events#emails_autocomplete"
  get "sync_calendar" => "events#sync_calendar"

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :case

	belongs_to :user
	has_many  :secondary_owners, through: :notes_users, class_name: 'User'
	has_many :notes_users, foreign_key: 'secondary_note_id'

	belongs_to :firm

	include PgSearch
  	pg_search_scope :search_note, against: [:note, :note_type],
                  using: {tsearch: {dictionary: :english, prefix: true}},
                  associated_against: { :user => :name , :case => :name }

	attr_accessor :add_task, :task_name, :task_due_date, :task_sms_reminder, :task_email_reminder,
								:task_description, :task_estimated_time, :task_estimated_time_unit,
								:task_owner_id, :task_secondary_owner_id, :task_add_event, :task_calendar_id

	accepts_nested_attributes_for :notes_users,
																:reject_if => :all_blank,
																:allow_destroy => true
	def self.notes_scope
		self
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  respond_to :html, :json
  before_filter :authenticate_user!
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :set_user, :set_firm, :get_case

  helper DatesHelper

  # GET /notes
  # GET /notes.json
  def index

    @user = current_user

    if get_case
      @notes = @case.notes.order("created_at desc")
      # @my_notes = @notes.joins(:case => [{:contacts => :user}]).where(:contacts => {:user_account_id => @user.id})
      @my_notes = @case.notes.where(:user => current_user)
      @my_secondary_notes = @case.notes.joins(:notes_users).where('notes_users.secondary_owner_id = ?', current_user.id)

      @new_path = new_case_note_path(@case)
      @notes_a = [@case, Note.new] #for modal partial rendering
      # puts "MY NOTES -0-0-0-0-0-0-0-0- " + @my_notes.to_sql.inspect
    else
      @notes = @firm.notes.joins(:case, :user).preload(:case, :user).order("created_at desc")

      @my_notes = @user.notes.joins(:case, :user).preload(:case, :user)
      @my_secondary_notes = @user.secondary_notes.joins(:case, :user).preload(:case, :user)
      @new_path = new_note_path
      @notes_a = Note.new #for modal partial rendering
    end

    respond_to do |format|
      format.html
      format.json { render json: NotesDatatable.new(view_context, current_user, false, false, @case) }
    end

  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])
    restrict_access("notes") if @note.firm_id != @firm.id    
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
    restrict_access("notes") if @note.firm_id != @firm.id     
  end

  # POST /notes
  # POST /notes.json
  def create

    if get_case
      @note = @case.notes.build(note_params)
      path_notes = case_notes_path
    else
      @note = Note.new(note_params)
      path_notes = notes_path
    end
    @note.user = @user
    @note.firm = @firm

    respond_to do |format|
      if @note.save
        if note_params[:notes_users_attributes]
          count_cc = note_params[:notes_users_attributes].count
          last_notes_user = NotesUser.last(count_cc)
          last_notes_user.each do |notification|
            notification.notifications.create(content: @note.note, author: @note.author, note_id: @note.id, user_id: notification.secondary_owner_id)
          end
        end
        track_activity @note
        if note_params[:add_task]
          task = Task.new(name: note_params[:task_name], due_date: note_params[:task_due_date], sms_reminder: note_params[:task_sms_reminder],
                             email_reminder: note_params[:task_email_reminder], description: note_params[:task_description],
                             user_id: @user.id, firm_id: @firm.id, owner_id: note_params[:task_owner_id], secondary_owner_id: note_params[:task_secondary_owner_id],
                             case_id: note_params[:case_id], calendar_id: note_params[:task_calendar_id])
          if task.save
            if task.due_date.present?
              task.create_event
            end
          end
        end
        format.html { redirect_to path_notes, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    @user = current_user
    @note.user = @user
    respond_to do |format|
      if @note.update(note_params)
        track_activity @note
        format.html { respond_with @note, notice: 'Note was successfully updated' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @user = current_user
    @note.destroy
    track_activity @note
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully deleted' }
      format.json { head :no_content }
    end
  end

  def user_notes
    respond_to do |format|
      format.json { render json: NotesDatatable.new(view_context, current_user, true, false, get_case) }
    end
  end

  def case_user_notes
    if get_case
      puts " GET CASE: " + params[:case_id].to_s
      @case = Case.find(params[:case_id])
    end
    respond_to do |format|
      format.json { render json: NotesDatatable.new(view_context, current_user, true, true, @case) }
    end
  end

  def case_notes_case
    respond_to do |format|
      format.json { render json: NotesDatatable.new(view_context, current_user, false, true, get_case) }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:note, :case_id, :user_id, :case_alert, :firm_id, :note_type, :created_at, :updated_at, :author,
                                   :task_name, :task_due_date, :task_sms_reminder, :task_email_reminder, :add_task,
                                   :task_description, :task_owner_id, :task_secondary_owner_id,
                                   :task_add_event, :task_calendar_id, :secondary_note_id, :secondary_owner_id,
                                   :notes_users_attributes => [:id, :secondary_note_id, :secondary_owner_id, :_destroy])

    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_case_alert.html.erb
<% shown_title = false %>
<% if @case %>
  <% @case.notes.each do |note| %>
      <% if note.case_alert %>
      <div class="row">
      <div class="col-md-3">
      </div>
        <div class="col-md-6">
          <div class="case-alert">
            <div class="row">
                <div class="col-md-1">
              <span style="color: white; font-size: 24px; margin-top: 5px;" class="glyphicon glyphicon-exclamation-sign" ></span>
              </div>
              <div class="col-md-8">
            <% unless shown_title %>
                <strong>Case Alert</strong><br />
            <% end %>
            <% shown_title = true %>
            <%= note.note %>
            </div>
            <div class="col-md-3">
            <div style="float: right;color: #0088CC;margin-top: 10px;">
              <%= link_to "View Note", note_path(note), :style => "color: #0088CC;" %>
            </div>
            </div>
            </div>
          </div>
          </div>
        </div>
      <% end %>
  <% end %>
<% end %>

app/views/notes/_form.html.erb
<%= javascript_include_tag 'notes/form', 'data-turbolinks-track' => true %>
<%= simple_form_for(@notes_a) do |f| %>
      <%= f.error_notification %>

    <% if action_name == "index" || (controller_name == 'dashboards' && action_name == 'new') %>
      <!--only render html from 'if' to 'end' if the controller action this form was rendered from was 'index'; reason for this is because this form is used in 'new' and 'edit' actions; reason we aren't checking for if action_name == 'new' is because this is a modal that is rendered from the index action -->
      <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
             <a class="close" style="padding-top: 15px;" data-dismiss="modal">×</a>
              <h1>New Note</h1>
            </div>
         <div class="modal-body">
    <% end %>

    <table class="note-form table-condensed">
        <tbody>
          <tr>
              <td>
                  <strong>Author:</strong>
              </td>
              <td>
                  <%= f.text_field :author, :readonly => true, :value => @user.name, label: false, :class => 'table-input' %>
                    <%= link_to_add_association 'Add cc', f, :notes_users,:"data-association-insertion-node" => "div#notess", :"data-association-insertion-method" => "append", :partial => "notes_user_fields", class: 'user pull-right' %>
              </td>
          </tr>
          <tr >
            <td>
              <div id="popup_note"></div>
            </td>
            <td>
              <div id="notess">
                <%= f.simple_fields_for :notes_users, NotesUser.new do |user| %>
                  <% if !user.object.id.nil? %>
                    <%= render 'notes_user_fields', :f => user %>
                  <% end %>
                <% end %>
              </div>
            </td>
          </tr>
          <tr>
              <td>
                  <strong>Created:</strong>
              </td>
              <td>
                  <%= Date.today %>
              </td>
          </tr>
          <tr>
              <td>
                  <strong>Case:</strong>
              </td>
              <td>
               <% if !@case %>
                  <%= f.association :case, :collection => @firm.cases, :input_html => {:id => "note_select"}, label: false %>
               <% else %>
                  <%= @case.name %>
               <% end %>
              </td>
          </tr>
          <tr>
              <td>
                  <strong>Type:</strong>
              </td>
              <td>
                  <%= f.select :note_type, ['General', 'Update','Status Update', 'Phone Call', 'Email', 'Communication w/ Client', 'Medical/Review', 'Treatment Update', 'Done Treating', 'Property Damage', 'Adjustor Update', 'Deposition', 'Lit Follow Up', 'Settlement Offer', 'Settlement Demand' ], label: false, :class => 'table-input' %>
              </td>
          </tr>
          <tr>
              <td class="big-row">
                  <Strong>Note:</Strong>
              </td>
              <td class="big-row">
                  <%= f.text_area :note, label: false, :class => 'table-text' %>
              </td>
          </tr>
          <tr>
            <td>
            </td>
            <% if !@case %>
              <td class="case_alert">
                <%= f.check_box :case_alert, {}, true, false  %> Make this note a Case Alert
              </td>
            <% else %>
              <td>
                <%= f.check_box :case_alert, {}, true, false  %> Make this note a Case Alert
              </td>
            <% end %>
          </tr>
<% if false %> <!-- START OF COMMENT -->
          <tr>
            <td>
              <strong>Add Task:</strong>
            </td>
            <td>
              <%= f.check_box :add_task, {}, true, false %>
            </td>
          </tr>

            <tr class="task_field">
              <td>
                <strong>Task:</strong>
              </td>
              <td>
                <%= f.text_field :task_name, label: false, :class => 'table-input' %>
              </td>
            </tr>
            <tr class="task_field">
              <td>
                <strong>Task Owner: </strong>
              </td>
              <td>
                <%= f.select :task_owner_id, @firm.users.map {|u| [u.name, u.id]}, :selected => current_user.id, :input_html => {:id => "owner_select"}, label: false %>
              </td>
            </tr>
            <tr class="task_field">
              <td>
                <strong>Secondary Owner: </strong>
              </td>
              <td>
                <%= f.select :task_secondary_owner_id, @firm.users.map {|u| [u.name, u.id]}, :input_html => {:id => "secondary_owner_select"}, label: false, :include_blank => true %>
              </td>
            </tr>
            <tr class="task_field">
              <td>
                <strong>Due Date:</strong>
              </td>
              <td>
                <%= f.date_field :task_due_date, label: false, :class => 'table-input' %>
              </td>
            </tr>
            <tr class="task_field">
              <td>
                <strong>Task Description:</strong>
              </td>
              <td class="big-row">
                <%= f.text_area :task_description, label: false, :class => 'table-text' %>
              </td>
            </tr>            
            <tr class="task_field">
              <td>
                <strong>Add to My Calendar:</strong>
              </td>
              <td> 
                <%= f.check_box :task_add_event, {:checked => true}, true, false %>
                
                <%= f.select :task_calendar_id, @user.active_calendars.map{ |c| ["#{c.namespace.full_name}: #{c.name}", c.id] }, include_blank: true, label: false, :class => 'table-input' %>
              </td>
            </tr>
<% end %> <!-- END OF COMMENT -->
        </tbody>
    </table>
    <br>
        <% if action_name == "index" || (controller_name == 'dashboards' && action_name == 'new') %>
          </div><!--end of modal-body-->
          
           <div class="modal-footer">
              <div class="pull-left">
                <a class="close" data-dismiss="modal">Cancel</a> 
              </div>
        <% end %>

              <div class="form-actions">
                  <%= f.button :submit, :class =>"btn btn-info", :style => 'font-size: 18px;' %>
              </div>

    <% if action_name == "index" || (controller_name == 'dashboards' && action_name == 'new') %>
            </div><!--end of modal-footer-->
        </div><!--end of modal-content-->
      </div><!--end of modal-dialog-->
    <% end %>

<% end %>

app/views/notes/_notes_index_javascript.html.erb
<% content_for :javascript do %>
<script type="text/javascript">
    $(document).ready(function() {
        $('#new_modal').click(function(event){
            $("#modal-window").html("<%= escape_javascript(render 'notes/form', new_note: @note_a ) %>");
        });
        $('.table tbody').on( 'click', 'tr', function (e) {
            var id = $(e.currentTarget).data('id');
            $('table.rowlink').rowlink()
        });

        var notes_scope = {user_notes: 'notes_scope', case_user_notes: 'notes_scope', notes: 'notes_scope', case_notes_case: 'notes_scope'};

        $('.table').each(function(i, table) {
            $(table).dataTable({
                language: {
                    search: "_INPUT_",
                    searchPlaceholder: "Search",
                    lengthMenu: "View _MENU_"
                },
                sDom: '<"toolbar">Rfrtlip',
                aaSorting: [[ 0, "desc" ]],
                bProcessing: true,
                bServerSide: true,
                sAjaxSource: $(table).data('source'),
                fnServerParams: function ( aoData ) {
                    aoData.push( {'name': "notesScope", 'value': notes_scope[$(table).attr('id')] } );
                }
            });
        });

    });
</script>
<% end %>

app/views/notes/_table.html.erb
<%= javascript_include_tag 'notes/table', 'data-turbolinks-track' => true %>
<div class="table-responsive">
  <table id="<%= id %>" class="table table-striped table-hover rowlink notes_table" data-source="<%= send("#{id}_path") %>">
    <thead class="user-table-head">
    <tr>
      <th>Case</th>
      <th>Author</th>
      <th>Note</th>
      <th>Created</th>
      <th>Note Type</th>
    </tr>
    </thead>
    <tbody>
    </tbody>
  </table>
</div>

app/views/notes/new.html.erb
<h1>New Note</h1>
<br>
<div style="width: 800px;">
		<%= render 'form', new_note: @note %>
	<div class="pull-right">
        <%= link_to "Cancel", user_root_path(@user), :class => 'close' %>
    </div>
</div>

app/views/notes/show.html.erb
<%= javascript_include_tag 'notes/show', 'data-turbolinks-track' => true %>
<div class="text-center">
<table id="info-table4">
  <tbody>
    <tr>
      <td id="left-td"><%= link_to :back,  :class => 'dark' do %><span id="back" title="Back to Notes" class="glyphicon glyphicon-arrow-left"></span> <% end %></td>
      <td>
      </td>
      <td>
      </td>
      <td><%= link_to @note, :class => 'dark-right', method: :delete, data: { confirm: 'WARNING! Deleting a note will remove all the information from storage and you will not be able to retrieve it. Would you like to delete anyway?' } do %><span id="delete" class="glyphicon glyphicon-trash" title="Delete Note"></span> <% end %>
       <%= link_to "",  :class => 'dark-right' do %><span id="print" class="glyphicon glyphicon-print" title="Print Screen"></span> <% end %>
      <%= link_to 'Edit', edit_note_path(@note), :class => 'dark' %></td>
    </tr>
    </tbody>
  </table>
</div>

<table id="info-table3">
<thead>
  <tr class="right-top">
    <td colspan="3" class="gray-back">
      <strong>Note</strong>
    </td>
  </tr>
</thead>
  <tbody>
      <tr>
        <td class="right">
        <strong>Author:</strong>
        </td>
        <td colspan="2">
        <%= @note.user.try(:name) %>    
        </td>
      </tr>
      <tr>
        <td class="right">
          <strong>CC:</strong>
        </td>
        <td colspan="2">
          <% @note.try(:notes_users).each do |user| %>
              <%= user.secondary_owner.name %><br />
          <% end %>
        </td>
      </tr>
      <tr>
        <td class="right">
          <strong>Creation Date:</strong>
        </td>
        <td colspan="2">
          <%= simple_format_datetime_regexp @note.created_at %>
        </td>
      </tr>
      <tr>
        <td class="right">
          <strong>Case:</strong>
        </td>
        <td class="doc-link" colspan="2">
          <%= link_to @note.case.name,  case_path(@note.case) if @note.case.present? %>
        </td>
      </tr>
      <tr>
        <td class="right">
          <strong>Type:</strong>
        </td>
        <td colspan="2">
          <%= @note.note_type %>
        </td>
      </tr>
        <tr>
        <td class="right big-row">
          <strong>Note:</strong>
        </td >
        <td colspan="2" class="big-row">
          <%= @note.note %>
        </td>
      </tr>
      <tr>
        <td class="right">
          <strong>Case Alert?</strong>
        </td >
        <td colspan="2">
          <%= boolean_as_yesno @note.case_alert %>
        </td>
      </tr>
  </tbody>
</table>