config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  resources :activities
  get '/analytics' => 'analytics#index'
  get '/charts/data' => 'analytics#get_case'

  authenticated :user do
    mount Resque::Server.new, at: '/resque'
  end

  get 'reports' => 'reports#index', as: :reports
  get 'reports/show' => 'reports#show', as: :report_show
  get 'reports/all_leads_by_channel' => 'reports#leads_by_channel_report', as: :reports_leads_by_channel
  get 'reports/all_leads_detail/(:marketing_channel_arg)(.:format)' => 'reports#leads_detail_report', as: :reports_leads_detail
  get 'reports/cases_statute_of_limitations' => 'reports#case_sol_report', as: :reports_case_sol
  get 'reports/open_close' => 'reports#open_close_report', as: :reports_open_close
  get 'reports/medical_bills_totals' => 'reports#medical_bills_report', as: :reports_medical_bills
  get 'reports/cases_by_user' => 'reports#cases_by_user_report', as: :reports_cases_by_user
  get 'reports/cases_by_statuses' => 'reports#cases_by_status_report', as: :reports_cases_by_status
  get 'reports/count_of_cases_by_statuses' => 'reports#count_of_cases_by_status_report', as: :reports_count_of_cases_by_status
  get 'reports/open_close_detail_report' => 'reports#open_close_detail_report', as: :reports_open_close_detail

  resources :company_olds
  resources :templates
  patch 'templates/update_html/:id' => 'templates#update_html'
  get 'templates/generate_document/:id' => 'templates#generate_document', as: :generate_document
  post 'templates_get_case' => 'templates#get_case', as: :get_case
  post 'templates_get_addressee' => 'templates#get_addressee', as: :get_addressee_attrs
  post 'templates_generate_docx' => 'templates#generate_docx', as: :generate_docx
  post 'settlement_generate_docx' => 'settlements#generate_docx', as: :settlement_generate_docx
  get 'settlement_download_docx/:id' => 'settlements#download_docx', as: :settlement_download_docx
  get 'download_docx/:id' => 'templates#download_docx', as: :download_docx
  post 'upload_docx' => 'templates#upload_docx', as: :upload_docx

  resources :time_entries, :except => [:new]
  put 'set_timer' => 'time_entries#set_timer', as: :set_timer
  put 'get_timer' => 'time_entries#get_timer', as: :get_timer
  put 'reset_timer' => 'time_entries#reset_timer', as: :reset_timer

  resources :task_lists
  post 'task_lists/import_to_case' => 'task_lists#import_to_case', as: :task_lists_import_to_case
  resources :firms
  resources :notes

  get '/documents/preview/:id' => 'documents#preview'
  resources :documents
  resources :plans
  get 'subscriptions/:id/change_plan/:plan_id' => 'subscriptions#change_plan', as: :change_plan
  get 'subscriptions/:id/edit_card/' => 'subscriptions#edit_card', as: :edit_card
  resources :subscriptions
  mount StripeEvent::Engine => '/payment-webhook'
  get '/events/email' => 'events#emails_autocomplete'
  resources :events

  resources :client_intakes, as: 'leads'
  get '/client_intakes_contacts/:id' => 'client_intakes#show_lead_contact', as: :lead_contact
  get '/client_intakes_contacts/:id/edit' => 'client_intakes#edit_lead_contact', as: :edit_lead_contact
  get '/client_intakes_documents/:id' => 'client_intakes#lead_documents', as: :lead_documents
  get '/client_intakes/:id/acceptance_letter' => 'client_intakes#acceptance_letter', as: :acceptance_letter

  resources :tasks
  post 'tasks/complete_task' => 'tasks#complete_task'
  get 'get_tasks' => 'tasks#get_tasks', as: :get_tasks
  match "/notifications/remove_all", to: "notifications#remove_all", via: [:delete], as: :remove_all_notifications
  resources :notifications


  resources :contacts
  post '/contacts/fly_create_contact' => 'contacts#fly_create_contact' ,as: :fly_contact, :defaults => { :format => :json }
  get '/companies' => 'contacts#companies', as: :companies
  get '/companies/:id' => 'contacts#show_company', as: :company
  get '/companies/:id/edit' => 'contacts#edit_company', as: :edit_company

  resources :insights do
    collection do
      get :filter_cases
    end
  end
  
  authenticated :user do
    root :to => "dashboards#new", as: :user_root
    #root :to => 'business_account#dashboard', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Business' }, :as => "business_root"
  end

  root :to => "visitors#index"
  get '/onboarding' => 'dashboards#new'
  post '/save_confirm_step' => 'dashboards#save_step'
  get '/finish_registration' => 'dashboards#finish_registration'
  get '/dashboard/:id' => 'dashboards#show'
  get '/get_counties_by_state' => 'insights#get_counties_by_state'
  #post '/dashboard/:name' => 'dashboard#create_firm_contact', as: 'dashboard_create_firm_contact'
  #get '/dashboard/:id' => 'users#show', as: :user_root
  get '/auth/google_oauth2/callback' => 'users#save_google_oauth'
  get '/auth/failure' => 'users#fail_google_oauth'
  get 'refresh_events' => 'events#refresh_events'
  # get '/dashboards/select_calendar'
  post '/dashboards/select_calendar'
  get  "dropbox/main"
  post "dropbox/upload"
  get  "dropbox/auth_start"
  get  "dropbox/auth_finish"
  get 'login_callback' => 'nylas#login_callback'
  get 'login_callback_close' => 'nylas#login_callback_close'
  get 'login' => 'nylas#login'
  resources :namespaces
  post 'get_events' => 'namespaces#get_events', as: :get_events
  post 'get_calendars' => 'namespaces#get_calendars', as: :get_calendars
  post 'get_mass_calendar_events' => 'namespaces#get_mass_calendar_events', as: :get_mass_calendar_events
  delete 'namespaces/:id/:calendar_id' => 'namespaces#destroy_calendar', as: :calendar

  # Visitor routes
  get "/about" => 'visitors#about', as: :about
  get "/terms" => 'visitors#terms', as: :terms
  get "index" => 'visitors', as: :index
  get "/contact" => 'visitors#contactlitigo', as: :contactlitigo
  get "/privacy" => 'visitors#privacy', as: :privacy
  get "/pricing" => 'visitors#pricing', as: :pricing
  get "/partners" => 'visitors#partners', as: :partners
  get "/confirm" => 'visitors#confirm_signin_email', as: :confirm_signin_email

  resources :dashboards, path: "dashboard"

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions" , :invitations => 'invitations'}
  devise_scope :user do
    get 'users/profile' => 'registrations#profile'
    get 'users/settings' => 'registrations#settings'
    get 'users/admin' => 'registrations#admin'
    get '/confirm/:id' => 'registrations#confirm_signup_email', as: :confirm_signup_email
    patch '/users/update_profile' => 'registrations#update_profile'
    get "/users/invitation/existing_user_invited/:id" => 'invitations#existing_user_invited', as: :existing_user_invited
    post "edit_events_permit" => 'invitations#edit_events_permit', as: :edit_events_permit

  end

  resources :expenses
  resources :invoices do
    resources :payments, :only => [:index, :create], :shallow => true

    get 'download' => 'invoices#download'
    get 'invoice_payments' => 'payments#invoice_payments', :defaults => { :format => :json }
  end
  resources :users
  resources :cases do
    resources :contacts, :shallow => true
    resources :notes, :shallow => true
    resources :documents#, :shallow => true
    resources :tasks, :shallow => true
    resources :incidents
    resources :resolutions
    resources :medicals
    resources :insurances
    resources :expenses
    resources :interrogatories
    resources :settlements
  end

  get 'cases/:id/edit_case_insurances' => 'insurances#edit_case_insurances', as: :edit_case_insurances
  get 'cases/:id/edit_case_interrogatories' => 'interrogatories#edit_case_interrogatories', as: :edit_case_interrogatories
  get "cases/:id/summary" => 'cases#summary', as: :case_summary
  get "cases/:id/dates" => 'cases#case_dates', as: :case_dates
  get "user_cases" => "cases#user_cases", :defaults => { :format => :json }
  get "user_leads" => "client_intakes#user_leads", :defaults => { :format => :json }
  get "user_notes" => "notes#user_notes", :defaults => { :format => :json }
  get "user_contacts" => "contacts#user_contacts", :defaults => { :format => :json }  
  get "case_user_notes/:case_id/notes" => "notes#case_user_notes", :defaults => { :format => :json }, as: :case_user_notes
  get "case_notes_case/:case_id/notes" => "notes#case_notes_case", :defaults => { :format => :json }, as: :case_notes_case
  get 'firm_invoices' => 'invoices#firm_invoices', :defaults => { :format => :json }
  get "accept_case/:id" => 'client_intakes#accept_case', as: :accept_case
  get 'cases/:id/doc' => 'cases#doc', as: :doc
  get "contacts/:id/contact information" => 'contacts#info', as: :contact_info
  get "contacts/:id/personal information" => 'contacts#personal', as: :contact_personal
  get "contacts/:id/company information" => 'contacts#coinfo', as: :contact_coinfo
  get "contacts/:id/cases" => 'contacts#contact_cases', as: :contact_linked_cases

  get 'cases/:case_id/assign_contacts' => 'contacts#assign_contacts', as: :assign_contacts
  post 'cases/:case_id/update_case_contacts' => 'contacts#update_case_contacts', as: :update_case_contacts
  post 'cases/:id/copy' => 'cases#create', as: :copy_case_create
  get 'cases/:id/case_contacts' => 'cases#show_case_contacts', as: :show_case_contacts
  get 'cases/:id/edit_case_contacts' => 'cases#edit_case_contacts', as: :edit_case_contacts
  post 'cases/:id/update_case_contacts' => 'cases#update_case_contacts', as: :update_contacts_on_case

  get 'cases/:id/case_services' => 'cases#case_services', as: :get_case_services
  get 'cases/:id/case_expenses' => 'cases#case_expenses', as: :get_case_expenses

  get 'invoice_expenses' => 'invoices#expenses', as: :show_invoice_expenses
  get 'invoice_services' => 'invoices#services', as: :show_invoice_services
  get 'invoice_sum' => 'invoices#invoice_sum', as: :show_invoice_sum

  resources :medicals do
    resources :injuries
  end
  get "emails_autocomplete" => "events#emails_autocomplete"
  get "sync_calendar" => "events#sync_calendar"

app/models/document.rb
class Document < ActiveRecord::Base
	belongs_to :user
	belongs_to :firm
	belongs_to :lead

	has_many :case_documents, :dependent => :destroy
	has_many :cases, :through => :case_documents
	belongs_to :interrogatory

	mount_uploader :document, DocumentUploader

	before_destroy :clean_s3

	def file_extension
		document.try(:file).try(:extension)
	end

	def can_preview?
		document.try(:file).try(:extension)
	end

	def image?
		%w(png jpg jpeg bmp gif).include? file_extension
	end

	def docx?
		'docx' == file_extension.to_s
	end

	def pdf?
		'pdf' == file_extension.to_s
	end

	def xls?
		%w(xls).include? file_extension
	end

	def txt?
		%w(txt).include? file_extension
	end

	def xlsx?
		%w(xlsx xlsm).include? file_extension
	end

	def tmp_file
		tmp_file = nil
		if document.file
			file_content = document.file.read
			tmp_file = Tempfile.new(document.file.filename, nil, encoding: file_content.encoding )
			tmp_file.write file_content
			tmp_file.close
		end
		tmp_file.try(:path)
	end

	def txt_file
		content = ''
		File.open(tmp_file, 'r').each_line do |line|
			content << "<p>#{line}</p>"
		end
		content
	end

	def pdf_images
		images = []
		pdf = Magick::ImageList.new tmp_file
		tmp_path = Rails.root.join('public', 'tmp')
		#FileUtils::mkdir_p tmp_path
		Dir.mkdir(tmp_path) unless File.exists?(tmp_path)
		pdf.each_with_index { |page_img, i|
			filename = "#{id}_#{i}_pdf_page.jpg"
			page_img.write("#{tmp_path}/#{filename}")
			images << "/tmp/#{filename}"
		}
		images
	end

	def to_docx_html
		content = ''
		doc = Docx::Document.open tmp_file
		doc.paragraphs.each do |p|
			if p.node.xpath('w:r//w:lastRenderedPageBreak').present?
				content << %q(<div class="page-break"></div>) + p.to_html
			else
				content << p.to_html
			end
		end
		content
	end

	def to_xlsx_html
		content = ''
		workbook = Creek::Book.new tmp_file
		workbook.sheets.each do |worksheet|
			table = '<table>'
			worksheet.rows.each do |row|
				table << '<tr>'
				row.each do |key, value|
					table << "<td>#{value}</td>"
				end
				table << '</tr>'
			end
			table << '</table>'
			content << '<div class="page-break"></div>' unless content.blank?
			content << table
		end
		content
	end

	def to_xls_html
		content = ''
		workbook = Spreadsheet.open tmp_file
		workbook.worksheets.each do |worksheet|
			table = '<table>'
			worksheet.rows.each do |row|
				table << '<tr>'
				row.each do |value|
					table << "<td>#{value}</td>"
				end
				table << '</tr>'
			end
			table << '</table>'
			content << '<div class="page-break"></div>' unless content.blank?
			content << table
		end
		content
	end

	private
	  def clean_s3
	    document.remove!
	    #document.thumb.remove! # if you have thumb version or any other version
	  rescue Excon::Errors::Error => error
	    puts "Something has gone wrong"
	    false
	  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_document, only: [:show, :edit, :update, :destroy, :preview]
  before_action :set_user, :set_firm

  layout 'preview', only: [:preview]

  helper DatesHelper

  # GET /documents
  # GET /documents.json
  def index
    if get_case
      @documents = @case.documents
      @my_documents = @case.documents.where(:user => current_user)
      @new_path = new_case_document_path(@case)
      @documents_a = [@case, Document.new] #for modal partial rendering
    else
      @documents = @firm.documents.joins(:cases, :user).preload(:cases, :user)
      @my_documents = @user.documents.joins(:cases, :user).preload(:cases, :user)
      @new_path = new_document_path
      @documents_a = Document.new #for modal partial rendering
    end
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])
    restrict_access("documents") if @document.firm_id != @firm.id
    get_case
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
    restrict_access("documents") if @document.firm_id != @firm.id 
    if get_case
      @documents_a = [@case, @document] #for modal partial rendering
    else
      @documents_a = @document #for modal partial rendering
    end
  end

  # POST /documents
  # POST /documents.json
  def create
    if get_case
      @document = @case.documents.create(document_params)
      path_documents = case_documents_path
    else
      @document = Document.new(document_params)
      path_documents = documents_path
    end
    if document_params[:lead_id].present?
      path_documents = lead_documents_path(document_params[:lead_id])
    end

    @document.user = @user
    @document.firm = @firm

    respond_to do |format|
      if @document.save
        track_activity @document
        format.html { redirect_to path_documents, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update

     if get_case
      #@document = @case.documents.create(document_params)
      path_documents = case_documents_path
    else
      #@document = @document(document_params)
      path_documents = documents_path
    end

    respond_to do |format|
      if @document.update(document_params)
        track_activity @document
        format.html { redirect_to path_documents, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def preview
    if @document.can_preview?
      case true
        when @document.image?
          render 'documents/preview_img'
        when @document.docx?
          @docx = @document.to_docx_html
          render 'documents/preview_docx'
        when @document.txt?
          @xls = @document.txt_file
          render 'documents/preview_xls'
        when @document.xls?
          @xls = @document.to_xls_html
          render 'documents/preview_xls'
        when @document.xlsx?
          @xls = @document.to_xlsx_html
          render 'documents/preview_xls'
        when @document.pdf?
          @images = @document.pdf_images
          render 'documents/preview_pdf'
        else
          render 'documents/preview_invalid'
      end
    else
      render 'documents/preview_invalid'
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    if @document.lead.present? && params[:case_id].present?
      @document.case_documents.where(case_id: params[:case_id]).delete_all
    else
      @document.destroy
    end
    track_activity @document
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:author, :doc_type, :user_id, :lead_id, :template, :document, :case_ids => [])
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_documents_index_javascript.html.erb
<% content_for :javascript do %>
  <script type="text/javascript">
    $(document).ready(function() {
        $('#new_modal').click(function(event){
            $("#modal-window").html("<%= escape_javascript(render 'documents/form', new_document: @documents_a ) %>");
        });
        var table = $('.table').dataTable({
            aoColumnDefs: [
                { 'bSortable': false, 'aTargets': [ 5,6,7 ] }
            ],
            language: {
                search: "_INPUT_",
                searchPlaceholder: "Search or Filter",
                lengthMenu: "View _MENU_"
            },
            sDom: 'Rfrtlip'
        });

      $('.preview_doc').click(function() {
        $.ajax({
          url: '/documents/preview/' + $(this).attr('data-id')
        }).done(function(data) {
          $("#modal-window").html(data);
        })
      });
    });
  </script>
<% end %>

app/views/documents/_documents_show_javascript.html.erb
<% content_for :javascript do %>
  <script type='text/javascript'>
    $(function() {
        $('#print').tipsy({gravity: 'ne', fade: true});
        $('#back').tipsy({gravity: 'n', fade: true});
    });
  </script>
<% end %>

app/views/documents/_dropbox_chooser.html.erb
<%= javascript_include_tag 'documents/dropbox_chooser', 'data-turbolinks-track' => true %>
<div id="db-container">
	Document Link: <a id="db-chooser" class="dark" href="#" />
</div>

app/views/documents/index.html.erb
<% if @case %>
<div class="case-header">
  <div class="case-title">
    <div class="container-fluid" style="padding: 0;">
      <div class="row">
        <div class="col-md-8" style="font-size: 24px;">
          <strong><%= @case.name %></strong><br>
        </div>
      </div>
    </div>
    <div id="case-buttons" class="documents-dropdown-button">
      <ul>
        <li class="dropdown">
          <%= link_to "", class: 'dropdown-toggle action-button', id: 'task-list-bnt', data: {toggle: "dropdown", :style => 'display:inline;'} do %>
            NEW DOCUMENT
            <span class="caret"></span>
          <% end %>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1" style="margin-top: 10px;">
            <li style="padding: 0; display: inline;"><%= link_to "Upload Document from local", @new_path, { :id => "new_modal", :remote => true, 'data-toggle' => "modal", 'data-target' => '#modal-window'} %></li>
            <li role="presentation" style="padding: 0; display: inline;"><%= link_to 'Create New from template', templates_path %></li>
            <li role="presentation" style="padding: 0; display: inline;"><%= link_to 'Settlement Sheet ', new_case_settlement_path(case_id: @case.id) %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
<strong>Case #: </strong><%= @case.case_number %>
        <div class="container-fluid" style="padding: 0;">
              <div class="row">
                      <div class="col-md-12">
                            <%= render partial: 'shared/case_tabs' %>
                      </div>
              </div>
        </div>
    <%= render partial: 'notes/case_alert' %>
</div>
<div class="incase-tabs-gap">
</div>
<div class="index-table-space">
<h3>My Documents</h3>
</div>
<% else %>
  <div class="case-header">
          <div class="case-title">
                <div style="font-size: 24px;">
                      <strong>Documents</strong>
                </div>
                <div id="case-buttons">
                      <ul>
                          <li><%= render 'new_button' %></li>
                      </ul>
                </div>
          </div>
                      <strong style="color: white;">A</strong>
          <div class="container-fluid" style="padding: 0;">
                  <div class="row">
                            <div class="col-md-12">
                                    <%= render 'shared/doc_tabs' %>
                            </div>
                  </div>
          </div>
  </div>
<div class="incase-tabs-gap">
</div>
<div class="index-table-space">
      <h3>My Documents</h3>
</div>
<% end %>
<div class="table-responsive">
      <table id="my_docs" class="table table-striped">
        <thead class="user-table-head">
        <tr>
          <th>Author</th>
          <th>Case</th>
          <th>Document Type</th>
          <th>Document Title</th>
          <th>Creation Date</th>
          <th>View</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        <% @my_documents.each do |document| %>
          <tr data-id="<%= document.id %>">
            <td><div class="larger-td"><%= document.user.try(:name) %></div></td>
            <td><%= document.cases.map {|c| c.name}.join(', ') %></td>
            <td><%= document.doc_type %></td>
            <td>
            <div class="doc-link">
              <%= if !document.document_url.blank?
                  link_to document.document.file.filename, document.document_url
                  end %></div></td>
            <td><%= simple_format_datetime_slash_regexp document.created_at  %></td>
            <td>
              <%= link_to document,  :class => 'dark-small preview_doc', 'data-id' => document.id, :remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window' do %> <span data-tip="Preview" class="glyphicon glyphicon-eye-open tip"></span> <% end %>
            </td>
            <td>
              <% if @case %>
                <%= link_to case_document_path(id: document.id, case_id: @case.id),  :class => 'dark-small' do %><span data-tip="Edit" class="glyphicon glyphicon-pencil tip"></span> <% end %>
              <% else %>
                <%= link_to document_path(document),  :class => 'dark-small' do %><span data-tip="Edit" class="glyphicon glyphicon-pencil tip"></span> <% end %>
              <% end %>
            </td>
            <td>
              <% if @case %>
                <%= link_to  document_path(id: document.id, case_id: @case.id),  method: :delete, data: { confirm: 'Are you sure you want to delete this document?' }, :class => 'dark-small' do %><span class="glyphicon glyphicon-trash tip" data-tip="Delete"></span><% end %>
            <% else %>
                <%= link_to  document,  method: :delete, data: { confirm: 'Are you sure you want to delete this document?' }, :class => 'dark-small' do %><span class="glyphicon glyphicon-trash tip" data-tip="Delete"></span><% end %>
              <% end %>
           </td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>
<br />
<br />
<div style="margin-top: 70px;">
<% if @case %>
<h3>Case Documents</h3>
<% else %>
<h3>All Firm Documents</h3>
</div>
<% end %>
    <div class="table-responsive">
      <table id="firm_docs" class="table table-striped">
        <thead class="user-table-head">
        <tr>
          <th>Author</th>
          <th>Case</th>
          <th>Document Type</th>
          <th>Document Title</th>
          <th>Creation Date</th>
          <th>View</th>
          <th>Edit</th>
          <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        <% @documents.each do |document| %>
          <tr data-id="<%= document.id %>">
            <td><div class="larger-td"><%= document.user.try(:name) %></div></td>
            <td><%= document.cases.map {|c| c.name}.join(', ') %></td>
            <td><%= document.doc_type %></td>
            <td>
            <div class="doc-link">
              <%= if !document.document_url.blank?
                  link_to document.document.file.filename, document.document_url
                  end %></div></td>
            <td><%= simple_format_date_regexp document.created_at  %></td>
            <td><%= link_to document_path(document),  :class => 'dark-small' do %><span data-tip="View" class="glyphicon glyphicon-eye-open tip"></span> <% end %>
            </td>
            <td><%= link_to edit_document_path(document),  :class => 'dark-small' do %><span data-tip="Edit" class="glyphicon glyphicon-pencil tip"></span> <% end %>
            </td>
            <td><%= link_to  document,  method: :delete, data: { confirm: 'Are you sure you want to delete this document?' }, :class => 'dark-small' do %><span class="glyphicon glyphicon-trash tip" data-tip="Delete"></span> <% end %>
           </td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>

  <%= render :partial => "documents_index_javascript" %>

app/views/documents/new.html.erb
<h1>New Document</h1>
<br>
<div style="width: 800px;">
		<%= render 'form', new_document: @document%>
	<div class="pull-right">
        <%= link_to "Cancel", user_root_path(@user), :class => 'close' %>
    </div>
</div>

app/views/documents/new.js.erb
<h1>New document</h1>

<%= render 'form', new_document: @document%>

<%= link_to 'Back', documents_path %>

app/views/documents/preview_docx.html.erb
<%= raw @docx %>

app/views/documents/preview_img.html.erb
<%= image_tag @document.document_url %>

app/views/documents/preview_invalid.html.erb
<h3>This document extension not supported yet</h3>

app/views/documents/show.html.erb
<div class="text-center">
<table id="info-table4">
  <tbody>
    <tr>
      <td id="left-td"><%= link_to :back,  :class => 'dark' do %><span id="back" title="Back" class="glyphicon glyphicon-arrow-left"></span> <% end %>
      </td>
      <td>
      </td>
      <td>
      </td>
      <td><%= link_to @document, :class => 'dark-right', method: :delete, data: { confirm: 'WARNING! Deleting a document will remove all the information from storage and you will not be able to retrieve it. Would you like to delete anyway?' } do %><span id="delete" class="glyphicon glyphicon-trash" title="Delete Document"></span> <% end %>
      <%= link_to 'Edit', edit_document_path(@document), :class => 'dark' %></td>
    </tr>
    </tbody>
  </table>
</div>

<table id="info-table3">
<thead>
  <tr class="right-top">
    <td colspan="3" class="gray-back">
      <strong>Document</strong>
    </td>
  </tr>
</thead>
  <tbody>
      <tr>
        <td class="right">
        <strong>Author:</strong>
        </td>
        <td colspan="2">
        <%= @document.user.try(:name) %>
        </td>
      </tr>
      <tr>
        <td class="right">
           <strong>Creation Date:</strong>
        </td>
        <td colspan="2">
          <%= simple_format_datetime_slash_regexp @document.created_at %>
        </td>
      </tr>     
       <tr>
        <td class="right">
          <strong>Case(s):</strong>
        </td >
        <td colspan="2">
          <div class="doc-link">
            <%= raw @document.cases.map {|c| link_to c.name, c}.join(', ') %>
          </div>
        </td>
      </tr>
      <tr>
        <td class="right">
          <strong>Description:</strong>
        </td>
        <td colspan="2">
          <%= @document.doc_type %>
        </td>
      </tr>
      <tr>
        <td class="right">
          <strong>Document:</strong>
        </td>
        <td colspan="2">
            <div class="doc-link">
                <% if @document.document.file %>
                    <%= link_to @document.document.file.filename, @document.document_url %>
                <% end %>
            </div>
        </td>
      </tr>
      
  </tbody>
</table>
<%= render :partial => "documents_show_javascript" %>