config/routes.rb
require 'resque/server'

Rails.application.routes.draw do

  resources :activities
  get '/analytics' => 'analytics#index'
  get '/charts/data' => 'analytics#get_case'

  authenticated :user do
    mount Resque::Server.new, at: '/resque'
  end

  get 'reports' => 'reports#index', as: :reports
  get 'reports/show' => 'reports#show', as: :report_show
  get 'reports/all_leads_by_channel' => 'reports#leads_by_channel_report', as: :reports_leads_by_channel
  get 'reports/all_leads_detail/(:marketing_channel_arg)(.:format)' => 'reports#leads_detail_report', as: :reports_leads_detail
  get 'reports/cases_statute_of_limitations' => 'reports#case_sol_report', as: :reports_case_sol
  get 'reports/open_close' => 'reports#open_close_report', as: :reports_open_close
  get 'reports/medical_bills_totals' => 'reports#medical_bills_report', as: :reports_medical_bills
  get 'reports/cases_by_user' => 'reports#cases_by_user_report', as: :reports_cases_by_user
  get 'reports/cases_by_statuses' => 'reports#cases_by_status_report', as: :reports_cases_by_status
  get 'reports/count_of_cases_by_statuses' => 'reports#count_of_cases_by_status_report', as: :reports_count_of_cases_by_status
  get 'reports/open_close_detail_report' => 'reports#open_close_detail_report', as: :reports_open_close_detail

  resources :company_olds
  resources :templates
  patch 'templates/update_html/:id' => 'templates#update_html'
  get 'templates/generate_document/:id' => 'templates#generate_document', as: :generate_document
  post 'templates_get_case' => 'templates#get_case', as: :get_case
  post 'templates_get_addressee' => 'templates#get_addressee', as: :get_addressee_attrs
  post 'templates_generate_docx' => 'templates#generate_docx', as: :generate_docx
  post 'settlement_generate_docx' => 'settlements#generate_docx', as: :settlement_generate_docx
  get 'settlement_download_docx/:id' => 'settlements#download_docx', as: :settlement_download_docx
  get 'download_docx/:id' => 'templates#download_docx', as: :download_docx
  post 'upload_docx' => 'templates#upload_docx', as: :upload_docx

  resources :time_entries, :except => [:new]
  put 'set_timer' => 'time_entries#set_timer', as: :set_timer
  put 'get_timer' => 'time_entries#get_timer', as: :get_timer
  put 'reset_timer' => 'time_entries#reset_timer', as: :reset_timer

  resources :task_lists
  post 'task_lists/import_to_case' => 'task_lists#import_to_case', as: :task_lists_import_to_case
  resources :firms
  resources :notes

  get '/documents/preview/:id' => 'documents#preview'
  resources :documents
  resources :plans
  get 'subscriptions/:id/change_plan/:plan_id' => 'subscriptions#change_plan', as: :change_plan
  get 'subscriptions/:id/edit_card/' => 'subscriptions#edit_card', as: :edit_card
  resources :subscriptions
  mount StripeEvent::Engine => '/payment-webhook'
  get '/events/email' => 'events#emails_autocomplete'
  resources :events

  resources :client_intakes, as: 'leads'
  get '/client_intakes_contacts/:id' => 'client_intakes#show_lead_contact', as: :lead_contact
  get '/client_intakes_contacts/:id/edit' => 'client_intakes#edit_lead_contact', as: :edit_lead_contact
  get '/client_intakes_documents/:id' => 'client_intakes#lead_documents', as: :lead_documents
  get '/client_intakes/:id/acceptance_letter' => 'client_intakes#acceptance_letter', as: :acceptance_letter

  resources :tasks
  post 'tasks/complete_task' => 'tasks#complete_task'
  get 'get_tasks' => 'tasks#get_tasks', as: :get_tasks
  match "/notifications/remove_all", to: "notifications#remove_all", via: [:delete], as: :remove_all_notifications
  resources :notifications


  resources :contacts
  post '/contacts/fly_create_contact' => 'contacts#fly_create_contact' ,as: :fly_contact, :defaults => { :format => :json }
  get '/companies' => 'contacts#companies', as: :companies
  get '/companies/:id' => 'contacts#show_company', as: :company
  get '/companies/:id/edit' => 'contacts#edit_company', as: :edit_company

  resources :insights do
    collection do
      get :filter_cases
    end
  end
  
  authenticated :user do
    root :to => "dashboards#new", as: :user_root
    #root :to => 'business_account#dashboard', :constraints => lambda { |request| request.env['warden'].user.class.name == 'Business' }, :as => "business_root"
  end

  root :to => "visitors#index"
  get '/onboarding' => 'dashboards#new'
  post '/save_confirm_step' => 'dashboards#save_step'
  get '/finish_registration' => 'dashboards#finish_registration'
  get '/dashboard/:id' => 'dashboards#show'
  get '/get_counties_by_state' => 'insights#get_counties_by_state'
  #post '/dashboard/:name' => 'dashboard#create_firm_contact', as: 'dashboard_create_firm_contact'
  #get '/dashboard/:id' => 'users#show', as: :user_root
  get '/auth/google_oauth2/callback' => 'users#save_google_oauth'
  get '/auth/failure' => 'users#fail_google_oauth'
  get 'refresh_events' => 'events#refresh_events'
  # get '/dashboards/select_calendar'
  post '/dashboards/select_calendar'
  get  "dropbox/main"
  post "dropbox/upload"
  get  "dropbox/auth_start"
  get  "dropbox/auth_finish"
  get 'login_callback' => 'nylas#login_callback'
  get 'login_callback_close' => 'nylas#login_callback_close'
  get 'login' => 'nylas#login'
  resources :namespaces
  post 'get_events' => 'namespaces#get_events', as: :get_events
  post 'get_calendars' => 'namespaces#get_calendars', as: :get_calendars
  post 'get_mass_calendar_events' => 'namespaces#get_mass_calendar_events', as: :get_mass_calendar_events
  delete 'namespaces/:id/:calendar_id' => 'namespaces#destroy_calendar', as: :calendar

  # Visitor routes
  get "/about" => 'visitors#about', as: :about
  get "/terms" => 'visitors#terms', as: :terms
  get "index" => 'visitors', as: :index
  get "/contact" => 'visitors#contactlitigo', as: :contactlitigo
  get "/privacy" => 'visitors#privacy', as: :privacy
  get "/pricing" => 'visitors#pricing', as: :pricing
  get "/partners" => 'visitors#partners', as: :partners
  get "/confirm" => 'visitors#confirm_signin_email', as: :confirm_signin_email

  resources :dashboards, path: "dashboard"

  devise_for :users, :controllers => {:registrations => "registrations", :sessions => "sessions" , :invitations => 'invitations'}
  devise_scope :user do
    get 'users/profile' => 'registrations#profile'
    get 'users/settings' => 'registrations#settings'
    get 'users/admin' => 'registrations#admin'
    get '/confirm/:id' => 'registrations#confirm_signup_email', as: :confirm_signup_email
    patch '/users/update_profile' => 'registrations#update_profile'
    get "/users/invitation/existing_user_invited/:id" => 'invitations#existing_user_invited', as: :existing_user_invited
    post "edit_events_permit" => 'invitations#edit_events_permit', as: :edit_events_permit

  end

  resources :expenses
  resources :invoices do
    resources :payments, :only => [:index, :create], :shallow => true

    get 'download' => 'invoices#download'
    get 'invoice_payments' => 'payments#invoice_payments', :defaults => { :format => :json }
  end
  resources :users
  resources :cases do
    resources :contacts, :shallow => true
    resources :notes, :shallow => true
    resources :documents#, :shallow => true
    resources :tasks, :shallow => true
    resources :incidents
    resources :resolutions
    resources :medicals
    resources :insurances
    resources :expenses
    resources :interrogatories
    resources :settlements
  end

  get 'cases/:id/edit_case_insurances' => 'insurances#edit_case_insurances', as: :edit_case_insurances
  get 'cases/:id/edit_case_interrogatories' => 'interrogatories#edit_case_interrogatories', as: :edit_case_interrogatories
  get "cases/:id/summary" => 'cases#summary', as: :case_summary
  get "cases/:id/dates" => 'cases#case_dates', as: :case_dates
  get "user_cases" => "cases#user_cases", :defaults => { :format => :json }
  get "user_leads" => "client_intakes#user_leads", :defaults => { :format => :json }
  get "user_notes" => "notes#user_notes", :defaults => { :format => :json }
  get "user_contacts" => "contacts#user_contacts", :defaults => { :format => :json }  
  get "case_user_notes/:case_id/notes" => "notes#case_user_notes", :defaults => { :format => :json }, as: :case_user_notes
  get "case_notes_case/:case_id/notes" => "notes#case_notes_case", :defaults => { :format => :json }, as: :case_notes_case
  get 'firm_invoices' => 'invoices#firm_invoices', :defaults => { :format => :json }
  get "accept_case/:id" => 'client_intakes#accept_case', as: :accept_case
  get 'cases/:id/doc' => 'cases#doc', as: :doc
  get "contacts/:id/contact information" => 'contacts#info', as: :contact_info
  get "contacts/:id/personal information" => 'contacts#personal', as: :contact_personal
  get "contacts/:id/company information" => 'contacts#coinfo', as: :contact_coinfo
  get "contacts/:id/cases" => 'contacts#contact_cases', as: :contact_linked_cases

  get 'cases/:case_id/assign_contacts' => 'contacts#assign_contacts', as: :assign_contacts
  post 'cases/:case_id/update_case_contacts' => 'contacts#update_case_contacts', as: :update_case_contacts
  post 'cases/:id/copy' => 'cases#create', as: :copy_case_create
  get 'cases/:id/case_contacts' => 'cases#show_case_contacts', as: :show_case_contacts
  get 'cases/:id/edit_case_contacts' => 'cases#edit_case_contacts', as: :edit_case_contacts
  post 'cases/:id/update_case_contacts' => 'cases#update_case_contacts', as: :update_contacts_on_case

  get 'cases/:id/case_services' => 'cases#case_services', as: :get_case_services
  get 'cases/:id/case_expenses' => 'cases#case_expenses', as: :get_case_expenses

  get 'invoice_expenses' => 'invoices#expenses', as: :show_invoice_expenses
  get 'invoice_services' => 'invoices#services', as: :show_invoice_services
  get 'invoice_sum' => 'invoices#invoice_sum', as: :show_invoice_sum

  resources :medicals do
    resources :injuries
  end
  get "emails_autocomplete" => "events#emails_autocomplete"
  get "sync_calendar" => "events#sync_calendar"

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_user, :set_firm
  
  def index
  end

  def show
  end

  def leads_by_channel_report
  	@start_date = params[:start_date] ? params[:start_date] : Date.today.at_beginning_of_month
  	@end_date = params[:end_date] ? params[:end_date] : Date.today
  	@leads_by_channel_report = LeadsByChannelReport.new(firm_id: @firm.id, start_date: @start_date, end_date: @end_date)
  end

  def leads_detail_report
  	@start_date = params[:start_date] ? params[:start_date] : Date.today.at_beginning_of_month
  	@end_date = params[:end_date] ? params[:end_date] : Date.today
    @marketing_channel_id_array = Lead::CHANNELS
  	@marketing_channel_arg = params[:marketing_channel_arg] && params[:marketing_channel_arg] != '' ? params[:marketing_channel_arg].split(",") : @marketing_channel_id_array
    @selected_marketing_channel = params[:marketing_channel_arg] if params[:marketing_channel_arg]
  	@leads_detail_report = LeadsDetailReport.new(firm_id: @firm.id, start_date: @start_date, end_date: @end_date, marketing_channel_arg: @marketing_channel_arg)
  end

  def case_sol_report
  	@start_date = params[:start_date] ? params[:start_date] : Date.today.at_beginning_of_month
  	@end_date = params[:end_date] ? params[:end_date] : Date.today.at_end_of_month
  	#puts 'PARAMS ATTORNEY ++++++++++++++ ' + params[:contact][:contact_id].inspect
    @attorney_staff_all_id_array = @firm.contacts.where("type IN ('Attorney', 'Staff')").pluck(:id)
    @attorney_staff = params[:contact] && params[:contact][:contact_id] != '' ? params[:contact][:contact_id].split(",").map(&:to_i) : @attorney_staff_all_id_array
    @selected_attorney = params[:contact][:contact_id] if params[:contact]
    #puts 'ATTTORNEY--------------- ' + @attorney.inspect
  	@case_sol_report = CaseSolReport.new(firm_id: @firm.id, start_date: @start_date, end_date: @end_date, attorney_contact_id: @attorney_staff)
  end

  def open_close_report
    @start_date = params[:start_date] ? params[:start_date] : Date.today.at_beginning_of_month
    @end_date = params[:end_date] ? params[:end_date] : Date.today.at_end_of_month
    @open_closed = params[:open_closed] ? params[:open_closed] : "Opened"
    @open_close_report = OpenCloseReport.new(firm_id: @firm.id, start_date: @start_date, end_date: @end_date, open_closed: @open_closed)
  end

  def medical_bills_report
    @case_all_id_array = @firm.cases.pluck(:id)
    @case_ = params[:case] && params[:case][:case_id] != '' ? params[:case][:case_id].split(",").map(&:to_i) : @case_all_id_array
    @selected_case = params[:case][:case_id] if params[:case]
    @medical_bills_report = MedicalBillsReport.new(firm_id: @firm.id, case_id_as_criteria: @case_)
  end

   def cases_by_user_report
    @user_all_id_array = []
    @firm.contacts.where("type IN ('Attorney', 'Staff')").each do |contact| 
      if User.exists?(contact.user_account_id)
        @user_all_id_array << contact.user_account_id 
      end
    end 
    @user_ = params[:contact] && params[:contact][:contact_id] != '' ? params[:contact][:contact_id].split(",").map(&:to_i) : @user_all_id_array.uniq
    @selected_user = params[:contact][:contact_id] if params[:contact]
    @statuses = params[:status] ? params[:status] : Case::STATUS
    #puts 'ATTTORNEY--------------- ' + @user_.inspect
    @cases_by_user_report = CasesByUserReport.new(firm_id: @firm.id, user_contact_id: @user_, status: @statuses)
  end

  def cases_by_status_report
    @case_status_id_array = Case::STATUS
    @case_status_arg = params[:case_status_arg] && params[:case_status_arg] != '' ? params[:case_status_arg].split(",") : @case_status_id_array
    @selected_case_status = params[:case_status_arg] if params[:case_status_arg]
    @cases_by_status_report = CasesByStatusReport.new(firm_id: @firm.id, case_status_arg: @case_status_arg)
  end

  def open_close_detail_report
    @start_date = params[:start_date] ? params[:start_date] : Date.today.at_beginning_of_month
    @end_date = params[:end_date] ? params[:end_date] : Date.today.at_end_of_month
    #puts 'PARAMS ATTORNEY ++++++++++++++ ' + params[:contact][:contact_id].inspect
    @open_close_detail_report = OpenCloseDetailReport.new(firm_id: @firm.id, start_date: @start_date, end_date: @end_date)
  end

  def count_of_cases_by_status_report
    all_statuses = Case::STATUS
    all_statuses.delete("Closed")
    all_statuses.delete("Inactive")
    open_statuses = all_statuses
    @open_count = Case.where(:firm_id => @firm.id, :status => open_statuses).count
    @closed_count = Case.where(:firm_id => @firm.id, :status =>  ['Inactive', 'Closed']).count
    
    @count_of_cases_by_status_report = CountOfCasesByStatusReport.new(firm_id: @firm.id)
  end  
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/case_sol_report.html.erb
<%= javascript_include_tag 'reports/cases_sol_report', 'data-turbolinks-track' => true %>
<%= form_tag reports_case_sol_path, method: :get do %>
<div class="case-header">
    <div class="case-title">
          <div style="font-size: 24px;">
                <strong>SOL Report</strong><br>
          </div>
            <div id="case-buttons">
              <ul>
             		<li><%= submit_tag "RUN REPORT", name: nil, :class => 'run-report' %></li>
              </ul>
          </div>
    </div>
    <!-- .collect {|contact| contact.name }) -->
        <div class="container-fluid" style="padding: 0; margin-top: 10px;">
              <div class="row">
                      <div class="col-md-2 col-xs-6">
                      	Start date<br>
                     			<%= date_field_tag :start_date, @start_date, :id => 'start-date' %>
                     	</div>
                     	<div class="col-md-2 col-xs-6">
                     	End date<br>
								<%= date_field_tag :end_date, @end_date, :id => 'end-date' %>
                      	</div>
                      	<div class="col-md-3 col-xs-6">
                      	Attorney or Staff<br>
                      		<%= collection_select :contact, :contact_id, @firm.contacts.where("type IN ('Attorney', 'Staff')"), :id, :name, :include_blank => true, :class => 'table-input', :selected => @selected_attorney %>
                      	</div>
                      	<div class="col-md-5 col-xs-12">
                      	</div>
              </div>
        </div>
</div>
<div class="incase-tabs-gap"></div>
<% end %>
<div style="margin-top: 72px;">
<div class="span6">
  <%= render template: 'dossier/reports/show', locals: {report: @case_sol_report.run} %>
</div>

app/views/reports/cases_by_status_report.html.erb
<%= javascript_include_tag 'reports/cases_by_status_report', 'data-turbolinks-track' => true %>
<%= form_tag reports_cases_by_status_path, method: :get do %>
<div class="case-header">
    <div class="case-title">
          <div style="font-size: 24px;">
                <strong>Cases by Status</strong><br>
          </div>
            <div id="case-buttons">
              <ul>
             		<li><%= submit_tag "RUN REPORT", name: nil, :class => 'run-report' %></li>
              </ul>
          </div>
    </div>
    <!-- .collect {|contact| contact.name }) -->
        <div class="container-fluid" style="padding: 0; margin-top: 10px;">
              <div class="row">
                      	<div class="col-md-3 col-xs-6">
                      	Case Status<br>
                      		<%= select_tag :case_status_arg, options_for_select(Case::STATUS, @selected_case_status), :include_blank => true, :class => 'table-input' %>
                      	</div>
                      	<div class="col-md-9 col-xs-6">
                      	</div>
              </div>
        </div>
</div>
<div class="incase-tabs-gap"></div>
<% end %>
<div style="margin-top: 72px;">
<div class="span6">
  <%= render template: 'dossier/reports/show', locals: {report: @cases_by_status_report.run} %>
</div>

app/views/reports/cases_by_user_report.html.erb
<%= javascript_include_tag 'reports/cases_by_user_report', 'data-turbolinks-track' => true %>
<%= form_tag reports_cases_by_user_path, method: :get do %>
<div class="case-header">
    <div class="case-title">
          <div style="font-size: 24px;">
                <strong>Cases by User</strong><br>
          </div>
            <div id="case-buttons">
              <ul>
             		<li><%= submit_tag "RUN REPORT", name: nil, :class => 'run-report' %></li>
              </ul>
          </div>
    </div>
    <!-- .collect {|contact| contact.name }) -->
        <div class="container-fluid" style="padding: 0; margin-top: 10px;">
              <div class="row">
                      	<div class="col-md-3 col-xs-6">
                      	User<br>
                      		<%= collection_select :contact, :contact_id, @firm.users.joins(:contacts).where("type IN ('Attorney', 'Staff')").uniq, :id, :name, :include_blank => true, :class => 'table-input', :selected => @selected_user %>
                      	</div>
                        <div class="col-md-3 col-xs-6">
                        Status<br>
                          <%= select_tag :status, options_for_select(Case::STATUS), multiple: true, :class => 'table-input', :placeholder => 'All Statuses' %>
                        </div>
                      	<div class="col-md-9 col-xs-6">
                      	</div>
              </div>
        </div>
</div>
<div class="incase-tabs-gap"></div>
<% end %>
<div style="margin-top: 72px;">
<div class="span6">
  <%= render template: 'dossier/reports/show', locals: {report: @cases_by_user_report.run} %>
</div>

app/views/reports/count_of_cases_by_status_report.html.erb
<%= javascript_include_tag 'reports/cases_by_status_report', 'data-turbolinks-track' => true %>
<%= form_tag reports_count_of_cases_by_status_path, method: :get do %>
<div class="case-header">
    <div class="case-title">
          <div style="font-size: 24px;">
                <strong>Cases by Status</strong><br>
          </div>
            <div id="case-buttons">
              <ul>
             		<li><%= submit_tag "RUN REPORT", name: nil, :class => 'run-report' %></li>
              </ul>
          </div>
    </div>
    <div class="container-fluid" style="padding: 0; margin-top: 10px;">
              <div class="row">
                        <div class="col-md-3 col-xs-6">
                        Total Open: <br>
                          <%= @open_count %>
                        </div>
                        <div class="col-md-3 col-xs-6">
                        Total Closed: <br>
                          <%= @closed_count %>
                        </div>
                        <div class="col-md-9 col-xs-6">
                        </div>
              </div>
        </div>
    
</div>
<div class="incase-tabs-gap"></div>
<% end %>
<div style="margin-top: 72px;">
<div class="span6">
  <%= render template: 'dossier/reports/show', locals: {report: @count_of_cases_by_status_report.run} %>
</div>

app/views/reports/index.html.erb
<div class="case-header">
      <div class="case-title">
          <div style="font-size: 24px;">
                  <strong>Reports</strong><br>
          </div>
              <div id="case-buttons">
                  <ul>
                        <li></li>
                  </ul>
            </div>
      </div>
      <strong style="color: white;">A</strong>
    <div class="container-fluid" style="padding: 0;">
        <div class="row">
            <div class="col-md-12">
                  
            </div>
        </div>
    </div>
</div>
        <div class="incase-tabs-gap"></div>
              <div style="margin-top: 50px;">
        </div>

      <div class="row">
            <div class="col-md-12">
                  <h3>Marketing Reports</h3>
            </div>
      </div>
      <div class="row">
            <div class="col-md-12 report-list">
                <ul>
                    <li><%= link_to "Leads By Channel Report", reports_leads_by_channel_path %></li>
                    <li><%= link_to "Leads Detail Report", reports_leads_detail_path %></li>
                </ul>
			     </div>
      </div>

<div>
  <div class="row">
            <div class="col-md-12">
                <h3>Case Management Reports</h3>
            </div>
  </div>
  <div class="row">
            <div class="col-md-12 report-list">
                <ul>
                    <li><%= link_to "Statute of Limitations Report", reports_case_sol_path %></li>
                    <li><%= link_to "Open / Closed Case Report", reports_open_close_path %></li>
                    <li><%= link_to "Medical Bills Report", reports_medical_bills_path %></li>
                    <li><%= link_to "Cases by User", reports_cases_by_user_path %></li>
                    <li><%= link_to "Cases by Status", reports_cases_by_status_path %></li>
                    <li><%= link_to "Count of Cases by Status", reports_count_of_cases_by_status_path %></li>                    
                    <li><%= link_to "Closed Case Report", reports_open_close_detail_path %></li>
                </ul>
            </div>
  </div>
</div>

app/views/reports/leads_by_channel_report.html.erb
<%= form_tag reports_leads_by_channel_path, method: :get do %>
<div class="case-header">
    <div class="case-title">
          <div style="font-size: 24px;">
                <strong>Leads by Channel</strong><br>
          </div>
            <div id="case-buttons">
              <ul>
             		<li><%= submit_tag "RUN REPORT", name: nil, :class => 'run-report' %></li>
              </ul>
          </div>
    </div>
    
        <div class="container-fluid" style="padding: 0; margin-top: 10px;">
              <div class="row">
                      <div class="col-md-2 col-xs-6">
                      	Start date<br>
                     			<%= date_field_tag :start_date, @start_date, :id => 'start-date' %>
                     	</div>
                     	<div class="col-md-2 col-xs-6">
                     	End date<br>
								<%= date_field_tag :end_date, @end_date, :id => 'end-date' %>
                      	</div>
                      	<div class="col-md-8">
                      	</div>
              </div>
        </div>
</div>
<div class="incase-tabs-gap"></div>
<% end %>
 <div style="margin-top: 72px;">
	<div class="span6">
		  <%= render template: 'dossier/reports/show', locals: {report: @leads_by_channel_report.run}%>
	</div>
</div>

app/views/reports/leads_detail_report.html.erb
<%= form_tag reports_leads_detail_path, method: :get do %>
<div class="case-header">
    <div class="case-title">
          <div style="font-size: 24px;">
                <strong>Leads by Channel</strong><br>
          </div>
            <div id="case-buttons">
              <ul>
             		<li><%= submit_tag "RUN REPORT", name: nil, :class => 'run-report' %></li>
              </ul>
          </div>
    </div>
    
        <div class="container-fluid" style="padding: 0; margin-top: 10px;">
              <div class="row">
                      <div class="col-md-2 col-xs-6">
                      	Start date<br>
                     			<%= date_field_tag :start_date, @start_date, :id => 'start-date' %>
                     	</div>
                     	<div class="col-md-2 col-xs-6">
                     	End date<br>
								<%= date_field_tag :end_date, @end_date, :id => 'end-date' %>
                      	</div>
                      	<div class="col-md-3 col-xs-6">
                      	Marketing Channel<br>
                      		<%= select_tag :marketing_channel_arg, options_for_select(Lead::CHANNELS, @selected_marketing_channel), :include_blank => true, :class => 'table-input' %>
                      	</div>
                      	<div class="col-md-5 col-xs-12">
                      	</div>
              </div>
        </div>
</div>
<div class="incase-tabs-gap"></div>
<% end %>
<div style="margin-top: 72px;">
	<div class="span6">
	  <%= render template: 'dossier/reports/show', locals: {report: @leads_detail_report.run} %>
	</div>
</div>

app/views/reports/medical_bills_report.html.erb
<%= javascript_include_tag 'reports/medical_bills_report', 'data-turbolinks-track' => true %>
<%= form_tag reports_medical_bills_path, method: :get do %>
<div class="case-header">
    <div class="case-title">
          <div style="font-size: 24px;">
                <strong>Medical Bills Report</strong><br>
          </div>
            <div id="case-buttons">
              <ul>
             		<li><%= submit_tag "RUN REPORT", name: nil, :class => 'run-report' %></li>
              </ul>
          </div>
    </div>
    <!-- .collect {|contact| contact.name }) -->
        <div class="container-fluid" style="padding: 0; margin-top: 10px;">
              <div class="row">
                	<div class="col-md-3 col-xs-6">
                	Case<br>
                		<%= collection_select :case, :case_id, @firm.cases, :id, :name, :include_blank => true, :class => 'table-input', :selected => @selected_case %>
                	</div>
                	<div class="col-md-5 col-xs-12">
                	</div>
              </div>
        </div>
</div>
<div class="incase-tabs-gap"></div>
<% end %>
<div style="margin-top: 72px;">
<div class="span6">
  <%= render template: 'dossier/reports/show', locals: {report: @medical_bills_report.run} %>
</div>

app/views/reports/open_close_detail_report.erb
<%= javascript_include_tag 'reports/open_close_detail_report', 'data-turbolinks-track' => true %>
<%= form_tag reports_open_close_detail_path, method: :get do %>
<div class="case-header">
    <div class="case-title">
          <div style="font-size: 24px;">
                <strong>Close Report</strong><br>
          </div>
            <div id="case-buttons">
              <ul>
             		<li><%= submit_tag "RUN REPORT", name: nil, :class => 'run-report' %></li>
              </ul>
          </div>
    </div>
    <!-- .collect {|contact| contact.name }) -->
        <div class="container-fluid" style="padding: 0; margin-top: 10px;">
              <div class="row">
                      <div class="col-md-2 col-xs-6">
                      	Start date<br>
                     			<%= date_field_tag :start_date, @start_date, :id => 'start-date' %>
                     	</div>
                     	<div class="col-md-2 col-xs-6">
                     	End date<br>
								<%= date_field_tag :end_date, @end_date, :id => 'end-date' %>
                      	</div>
                      	<div class="col-md-8 col-xs-12">
                      	</div>
              </div>
        </div>
</div>
<div class="incase-tabs-gap"></div>
<% end %>
<div style="margin-top: 72px;">
<div class="span6">
  <%= render template: 'dossier/reports/show', locals: {report: @open_close_detail_report.run} %>
</div>

app/views/reports/show.html.erb
<h1>Reports#show</h1>
<p>Find me in app/views/reports/show.html.erb</p>